### ISSUE TITLE
After branch renaming, the twilio-cli is not able to be upgraded or uninstalled

### ISSUE THREAD

**Issue by DanDanBiu** [twilio/homebrew-brew#9] opened 2020-12-22 19:23 UTC
Error message
```Warning: Twilio is switching the default branch from 'master' to 'main'
Warning: requiring an update to the default homebrew tap.
Warning:
Error: To upgrade twilio-cli, retap it with:
    brew untap twilio/brew
    brew tap twilio/brew
    brew upgrade twilio
```

However, the `brew untap twilio/brew` does not work.

**Comment by code-R** [comment] 2021-01-01 11:57
the above issue is happening for me as well and this is breaking everything related to brew, please suggest a fix/work around for this.

**Comment by thinkingserious** [comment] 2021-01-06 01:36
Hello @DanDanBiu, @code-R,

I have just tried to reproduce this without any luck. I have a few follow up questions:

1. What's the error you are seeing when you run `brew untap twilio/brew`? 
2. What OS?

Thanks!

With best regards,

Elmer

**Comment by AdityaAnand1** [comment] 2021-01-06 12:45
Yep, y'all broke brew.

This is the output I'm getting.

![image](https://user-images.githubusercontent.com/13274079/103769775-ebdf1600-504a-11eb-9a6b-4bb5a2a974de.png)


Ran into this when I was trying install (unrelated) aws cli thing and got stuck on this:

![image](https://user-images.githubusercontent.com/13274079/103769903-247eef80-504b-11eb-8a32-972d0d8f8875.png)

**Comment by thinkingserious** [comment] 2021-01-06 17:03
Thanks for the additional verification @AdityaAnand1!

From [this thread](https://discourse.brew.sh/t/brew-update-homebrew-core-is-a-shallow-clone/9300/17), it seems like this error is due to a recent policy update by homebrew. It looks like running the two commands that are suggested above in the error log should get things back to normal. Could you please verify? Thank you!

**Comment by billythemusical** [comment] 2021-01-06 19:27
I'm also having the same issue as @AdityaAnand1 without the shallow bits:
![Screen Shot 2021-01-06 at 2 26 26 PM](https://user-images.githubusercontent.com/40703526/103811610-2afd6f00-502b-11eb-8a8f-6708127bab82.png)

I'm on MacOSX Catalina 10.15.7

**Comment by DanDanBiu** [comment] 2021-01-07 00:18
Here is the error:

<img width="588" alt="Screen Shot 2021-01-06 at 4 17 17 PM" src="https://user-images.githubusercontent.com/5323204/103835299-b92d2180-503a-11eb-97ec-0cf81e2359e8.png">

OS: macOS Cataline 10.15.6

**Comment by AdityaAnand1** [comment] 2021-01-07 01:44
@thinkingserious if you look at the first image I shared, you'll see that `brew untap twilio/brew` results in an error that recommends running `brew untap twilio/brew` to fix the error.

**Comment by thinkingserious** [comment] 2021-01-07 01:57
Hello everyone, thanks for the updates and confirmations!

I'm going to need a bit more help trying to reproduce. I've tried on Big Sur and Catalina and I do not receive this error. Did others also see an error, similar to @AdityaAnand1, that requested executing the following commands?

@AdityaAnand1, I was referring to these commands:
`git -C /usr/local/Homebrew/Library/Taps/Homebrew/homebrew-core fetch -unshallow`
`git -C /usr/local/Homebrew/Library/Taps/Homebrew/homebrew-cask fetch -unshallow`

**Comment by TheRyanHickman** [comment] 2021-01-07 04:18
Brew is broken. Experiencing same. 

Mac OS Catalina 10.15.4 (19E287)

![image](https://user-images.githubusercontent.com/2328000/103850482-57d67400-5075-11eb-81f1-3dfb121c7612.png)


```
Warning: Twilio is switching the default branch from 'master' to 'main'
Warning: requiring an update to the default homebrew tap.
Warning:
Error: To upgrade twilio-cli, retap it with:
    brew untap twilio/brew
    brew tap twilio/brew
    brew upgrade twilio
 ```

**Comment by billythemusical** [comment] 2021-01-07 18:40
> Hello everyone, thanks for the updates and confirmations!
> 
> I'm going to need a bit more help trying to reproduce. I've tried on Big Sur and Catalina and I do not receive this error. Did others also see an error, similar to @AdityaAnand1, that requested executing the following commands?
> 
> @AdityaAnand1, I was referring to these commands:
> `git -C /usr/local/Homebrew/Library/Taps/Homebrew/homebrew-core fetch --unshallow`
> `git -C /usr/local/Homebrew/Library/Taps/Homebrew/homebrew-cask fetch --unshallow`

@thinkingserious I tried these commands, even though I was not prompted to, and it did not fix the error.  I am stuck on the same ``brew untap twilio/brew`` loop as others.

**Comment by thinkingserious** [comment] 2021-01-07 18:51
Thanks @TheRyanHickman and @billythemusical for the follow ups! I have an idea on how to recreate the issue and then work towards how to fix. I will attempt this today and report back here.

**Comment by thinkingserious** [comment] 2021-01-08 17:11
Hello everyone,

Could you please try running `brew update-reset $(brew --repo twilio/brew)`? Then try to upgrade or uninstall? Thanks!

**Comment by billythemusical** [comment] 2021-01-08 18:46
> Hello everyone,
> 
> Could you please try running `brew update-reset $(brew --repo twilio/brew)`? Then try to upgrade or uninstall? Thanks!

@thinkingserious that worked for me!! 🙏🏼 ty ty

**Comment by thinkingserious** [comment] 2021-01-08 23:19
I have also received confirmation of this fix internally, so I will close this one. Please reopen if you continue to experience any issues. Thank you!

**Closed by thinkingserious** 2021-01-08 23:19 UTC
Labels: status: waiting for feedback, type: question

**Comment by DanDanBiu** [comment] 2021-01-09 04:16
> Hello everyone,
> 
> Could you please try running `brew update-reset $(brew --repo twilio/brew)`? Then try to upgrade or uninstall? Thanks!

Works for me as well. Thanks a lot!

**Comment by JenniferMah** [comment] 2021-01-22 23:10
Hi folks,
If `brew update-reset $(brew --repo twilio/brew)` does not resolve the error please try to navigate to `/usr/local/Homebrew/Library/Taps/twilio/homebrew-brew` and manually switch to the main branch by using `git fetch && git checkout main`. If the you get an error about the main branch not existing, you can delete the tap with this command: `rm -rf /usr/local/Homebrew/Library/Taps/twilio/homebrew-brew`. Then you need to uninstall `brew uninstall twilio` and reinstalling with `brew tap twilio/brew` and `brew install twilio`. Thank you!

**Comment by Jntz** [comment] 2021-02-18 10:03
> Hello everyone,
> 
> Could you please try running `brew update-reset $(brew --repo twilio/brew)`? Then try to upgrade or uninstall? Thanks!

Thanks a lot! Finally get brew fixed
